// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Better Talk",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Better Talk",
            targets: ["AppModule"],
            bundleIdentifier: "Mugen.Rad.Better-Talk",
            teamIdentifier: "5UJL58M7XY",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Better Talk is designed to help users become better at using their voices. In order to proivde relavent feedback, it needs to hear you."),
                .speechRecognition(purposeString: "To maintain privacy when generating feedback. We'd like to process your audio on device.")
            ],
            appCategory: .lifestyle
        )
    ],
    dependencies: [
        .package(url: "https://github.com/dmrschmidt/DSWaveformImage", "14.2.1"..<"15.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "DSWaveformImage", package: "dswaveformimage"),
                .product(name: "DSWaveformImageViews", package: "dswaveformimage")
            ],
            path: "."
        )
    ]
)